version: '3'

services:
  test:
    depends_on:
      - service_diagnostics
    build: .
    image: app_diagnostics
    environment:
      REACT_APP_API_URL: http://service_diagnostics:8000
      REACT_APP_IS_LOCAL: 'true'
      IS_CI: ${ARG}
    command: |
      bash -c '
        yarn install
        if [ -z "${ARG}" ]
        then
          npx nodemon --exec "npx playwright test"
        else
          npx playwright test
        fi
      '
    volumes:
      - ./:/app
      - ./tests/mocks/images:/app/public/images
  service_diagnostics:
    image: python:3.8
    environment:
      FLASK_APP: mock_service_diagnostics.py
      FLASK_DEBUG: 'true'
      DIAGNOSTICS_URL: http://localhost:3000
      LOGIN_URL: http://localhost:4000
    working_dir: /app
    command: |
      bash -c '
        pip install flask
        pip install -U flask-cors
        cd tests/mocks && flask run --host=0.0.0.0 --port=8000
      '
    ports:
      - 8000:8000
    volumes:
      - ./:/app
