module.exports = {
    guitarConfig: {
        strings: 6,
        fretsOnChord: 4,
        name: 'Guitar',
        keys: [],
        tunings: {
            standard: ['E', 'A', 'D', 'G', 'B', 'E'],
        },
    },
    defaultChord: {
        key: '',
        frets: [0, 0, 0, 0, 0, 0],
        fingers: [0, 0, 0, 0, 0, 0],
        barres: [],
        capo: false,
        baseFret: 0,
    },
    chordsArray: [
        {
            key: 'a',
            frets: [1, 3, 3, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
        {
            key: 'b',
            frets: [1, 3, 2, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
        {
            key: 'c',
            frets: [-1, 3, 2, 0, 1, 0],
            fingers: [0, 3, 2, 0, 1, 0],
            barres: [1],
            capo: false,
        },
        {
            key: 'd',
            frets: [-1, -1, 0, 2, 3, 2],
            fingers: [0, 0, 0, 1, 3, 2],
            barres: [3],
            capo: false,
        },
        {
            key: 'e',
            frets: [0, 2, 2, 1, 0, 0],
            fingers: [0, 2, 3, 1, 0, 0],
            barres: [1],
            capo: false,
        },
        {
            key: 'f',
            frets: [1, 3, 3, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
        {
            key: 'f',
            frets: [1, 3, 3, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
        {
            key: 'f',
            frets: [1, 3, 3, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
        {
            key: 'f2',
            frets: [1, 3, 3, 2, 1, 1],
            fingers: [1, 3, 4, 2, 1, 1],
            barres: [1],
            capo: false,
        },
    ],
}
